--CREACION DE PROCEDIMIENTOS DE ALMACENAMIENTOS EN DB CIBIBLIOTECATI

USE
CIBIBLIOTECATI
GO

--PROCEDIMIENTO: REGISTRAR DE USUARIO 

CREATE PROCEDURE RegistrarUsuario_CIBIBLIOTECATI
@NOMBRES_USUARIO VARCHAR(50),
@APELLIDOS_USUARIO VARCHAR(50),
@ID_DEPARTAMENTO VARCHAR(50),
@ID_CARGO VARCHAR(50),
@UBICACION VARCHAR(50),
@N_EQUIPO VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO USUARIO
                         (NOMBRES_USUARIO, APELLIDOS_USUARIO, ID_DEPARTAMENTO, ID_CARGO, UBICACION, N_EQUIPO, FECHA_ACTUALIZACION)
VALUES        (@NOMBRES_USUARIO,@APELLIDOS_USUARIO,@ID_DEPARTAMENTO,@ID_CARGO,@UBICACION,@N_EQUIPO,@FechaModicacion)

END
GO

--PROCEDIMIENTO: IGRESAR DEPARTAMENTO

CREATE PROCEDURE RegistrarDepartamento_CIBIBLIOTECATI
@ID_DEPARTAMENTO VARCHAR(500),
@DESCRIPCION_DEPARTAMENTO VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN
	INSERT INTO DEPARTAMENTO
                         (ID_DEPARTAMENTO, DESCRIPCION_DEPARTAMENTO, FECHA_ACTUALIZACION)
VALUES        (@ID_DEPARTAMENTO, @DESCRIPCION_DEPARTAMENTO, @FechaModicacion)


END
GO

--PROCEDIMIENTO: IGRESAR CARGO

CREATE PROCEDURE RegistrarCargo_CIBIBLIOTECATI
@ID_DEPARTAMENTO VARCHAR(500),
@ID_CARGO VARCHAR(500),
@DESCRIPCION_CARGO VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO CARGOS
                         (ID_DEPARTAMENTO, ID_CARGO, DESCRIPCION_CARGO, FECHA_ACTUALIZACION)
VALUES        (@ID_DEPARTAMENTO, @ID_CARGO, @DESCRIPCION_CARGO, @FechaModicacion)

END
GO

CREATE PROCEDURE INSERTARUSUARIOSGESTORES
@Nombres VARCHAR(50),
@Apellidos VARCHAR(50),
@CargoID VARCHAR(500),
@DepartamentoID VARCHAR(500),
@Estado VARCHAR(50),
@Usuario VARCHAR(50),
@Contraseña VARCHAR(50),
@PermisoID INT

AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN
INSERT INTO USUARIOGESTOR
                         (Nombres, Apellidos, CargoID, DepartamentoID, Estado, Usuario, Contraseña, PermisoID, FECHA_ACTUALIZACION)
VALUES        (@Nombres,@Apellidos,@CargoID,@DepartamentoID,@Estado,@Usuario,@Contraseña,@PermisoID, @FechaModicacion)
END
GO

CREATE PROCEDURE LISTAUSUARIOSGESTORES
AS
BEGIN
 
SELECT        USUARIOGESTOR.Nombres, USUARIOGESTOR.Apellidos, DEPARTAMENTO.DESCRIPCION_DEPARTAMENTO, CARGOS.DESCRIPCION_CARGO, 
                         ESTADOSUSUARIO.Descripcion, USUARIOGESTOR.Usuario, USUARIOGESTOR.Contraseña, PERMISOSESTANDAR.Descripcion AS Expr1
FROM            USUARIOGESTOR INNER JOIN
                         DEPARTAMENTO ON USUARIOGESTOR.ID = DEPARTAMENTO.ID INNER JOIN
                         CARGOS ON USUARIOGESTOR.ID = CARGOS.ID INNER JOIN
                         ESTADOSUSUARIO ON DEPARTAMENTO.ID = ESTADOSUSUARIO.ID INNER JOIN
                         PERMISOSESTANDAR ON DEPARTAMENTO.ID = PERMISOSESTANDAR.ID

END
GO

--PROCEDIMIENTO: ELIMINAR FILA DE ACUAERDO AL ID


CREATE PROCEDURE EliminarDepartamento
@IDDEPARTAMENTO VARCHAR(50)
AS
BEGIN

DELETE FROM DEPARTAMENTO WHERE ID = @IDDEPARTAMENTO
-- Eliminar los cargos que esten afiliados a este departamento
-- DELETE FROM CARGOS WHERE ID_DEPARTAMENTO = @IDDEPARTAMENTO

END
GO

CREATE PROCEDURE EliminarCargo
@IDCARGO VARCHAR(50)
AS
BEGIN

DELETE FROM CARGOS WHERE ID = @IDCARGO

END
GO

CREATE PROCEDURE EliminarCliente
@IDCLIENTE VARCHAR(50)
AS
BEGIN

DELETE FROM USUARIO WHERE ID_USUARIO = @IDCLIENTE

END
GO

CREATE PROCEDURE EliminarUsuarios
@IDUSUARIOGESTOR VARCHAR(50)
AS
BEGIN

DELETE FROM USUARIOGESTOR WHERE ID = @IDUSUARIOGESTOR

END
GO


--PROCEDIMIENTO: MODIFICAR O ACTUALIZAR DATOS

CREATE PROCEDURE ActualizarDepartamento
@DESCRIPCIONDEPARTAMENTO VARCHAR(50),
@ID VARCHAR(50) 

AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN
UPDATE       DEPARTAMENTO
SET                DESCRIPCION_DEPARTAMENTO = @DESCRIPCIONDEPARTAMENTO, FECHA_ACTUALIZACION = @FechaModicacion
WHERE        (ID = @ID)

END
GO

CREATE PROCEDURE ActualizarCargo
@IDDEPARTAMENTO VARCHAR(500),
@DESCRIPCIONCARGO VARCHAR(50),
@ID VARCHAR(50) 

AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

UPDATE       CARGOS
SET                ID_DEPARTAMENTO = @IDDEPARTAMENTO, DESCRIPCION_CARGO = @DESCRIPCIONCARGO, FECHA_ACTUALIZACION = @FechaModicacion
WHERE        (ID = @ID)

END
GO

CREATE PROCEDURE ActualizarUsuario
@NOMBRES_USUARIO VARCHAR(50),
@APELLIDOS_USUARIO VARCHAR(50),
@CI INT,
@ID_DEPARTAMENTO VARCHAR(50),
@ID_CARGO VARCHAR(50),
@UBICACION VARCHAR(50),
@ESTADO VARCHAR(50),
@N_EQUIPO VARCHAR(50),
@ID_USUARIO VARCHAR(50) 

AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

UPDATE       USUARIO
SET                NOMBRES_USUARIO =@NOMBRES_USUARIO, APELLIDOS_USUARIO =@APELLIDOS_USUARIO, CI =@CI, ID_DEPARTAMENTO =@ID_DEPARTAMENTO, ID_CARGO =@ID_CARGO, UBICACION =@UBICACION, ESTADO = @ESTADO, N_EQUIPO =@N_EQUIPO, FECHA_ACTUALIZACION = @FechaModicacion
WHERE        (ID_USUARIO = @ID_USUARIO)

END
GO


--PROCEDIMIENTO: CONSULTA DE DEPARTAMENTO 

CREATE PROCEDURE ListaDepartamento_CIBIBLIOTECATI
AS
BEGIN
	SELECT * FROM DEPARTAMENTO
END
GO

CREATE PROCEDURE ListaDepartamentoPorID_CIBIBLIOTECATI
@ID_DEPARTAMENTO VARCHAR(50) 

AS
BEGIN
	SELECT * FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = @ID_DEPARTAMENTO
END
GO

--PROCEDIMIENTO: CONSULTA DE CARGO 

CREATE PROCEDURE ListaCargo_CIBIBLIOTECATI
AS
BEGIN

SELECT        CARGOS.ID, DEPARTAMENTO.DESCRIPCION_DEPARTAMENTO, CARGOS.ID_CARGO, CARGOS.DESCRIPCION_CARGO
FROM            DEPARTAMENTO INNER JOIN
                         CARGOS ON DEPARTAMENTO.ID = CARGOS.ID_DEPARTAMENTO

END
GO

CREATE PROCEDURE ListaCargoPorDepartamento_CIBIBLIOTECATI
@ID_DEPARTAMENTO VARCHAR(50) 

AS
BEGIN
	SELECT * FROM CARGOS WHERE ID_DEPARTAMENTO = @ID_DEPARTAMENTO
END
GO


--PROCEDIMIENTO: CONSULTA DE USUARIO 

CREATE PROCEDURE ListaUsuarios_CIBIBLIOTECATI

AS
BEGIN
	SELECT * FROM USUARIO
END
GO

--PROCEDIMIENTO: CONSULTA DE USUARIO GESTORES

CREATE PROCEDURE ListaUsuariosGestor_CIBIBLIOTECATI

AS
BEGIN
	SELECT * FROM USUARIOGESTOR
END
GO

--PROCEDIMIENTO: BUSCAR USUARIOS DE ACUAERDO A DIFERENTES CRITERIOS

CREATE PROCEDURE BuscarUsuarioPorNombre
@NOMBRE VARCHAR(50)

AS
BEGIN

SELECT * FROM USUARIO WHERE NOMBRES_USUARIO = @NOMBRE

END
GO

CREATE PROCEDURE BuscarUsuarioPorCedula
@CEDULA VARCHAR(50)

AS
BEGIN

SELECT * FROM USUARIO WHERE CI = @CEDULA

END
GO

--PROCEDIMIENTO: IGRESAR FECHA Y HORA 

CREATE PROCEDURE RegistrarUsuarioFecha_CIBIBLIOTECATI

@FECHA_REGISTRO DATETIME,
@FECHA_ACTUALIZACION DATETIME

AS
BEGIN

INSERT INTO USUARIO
                         (FECHA_REGISTRO, FECHA_ACTUALIZACION)
VALUES        (@FECHA_REGISTRO,@FECHA_ACTUALIZACION)

END
GO


















--PROCEDIMIENTO:  MODIFICAR PROCEDIMIENTO DE UN PROCEDURE YA CREADO

ALTER PROCEDURE RegistrarUsuario_CIBIBLIOTECATI
@NOMBRES_USUARIO VARCHAR(50),
@APELLIDOS_USUARIO VARCHAR(50),
@CI INT,
@ID_DEPARTAMENTO VARCHAR(50),
@ID_CARGO VARCHAR(50),
@UBICACION VARCHAR(50),
@ESTADO VARCHAR(50),
@N_EQUIPO VARCHAR(50),
@ULTIMO_ID INT OUTPUT 
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO USUARIO
                         (NOMBRES_USUARIO, APELLIDOS_USUARIO, CI, ID_DEPARTAMENTO, ID_CARGO, UBICACION, ESTADO, N_EQUIPO, FECHA_ACTUALIZACION)
VALUES        (@NOMBRES_USUARIO,@APELLIDOS_USUARIO,@CI,@ID_DEPARTAMENTO,@ID_CARGO,@UBICACION,@ESTADO,@N_EQUIPO,@FechaModicacion)

SET @ULTIMO_ID = SCOPE_IDENTITY()

RETURN @ULTIMO_ID

END
GO

















--EJECUCION DEL PROCEDIMIENTO: BuscarCompoentes_CMINVENTARIOTI

EXEC  ListaCargo_CIBIBLIOTECATI
GO