--CREACION DE PROCEDIMIENTOS DE ALMACENAMIENTOS EN DB CMINVENTARIOTI

USE
CMINVENTARIOTI
GO

--PROCEDIMIENTO: CONSULTA DE COMPONENTES 

CREATE PROCEDURE BuscarCompoentes_CMINVENTARIOTI
AS
BEGIN

SELECT * FROM COMPONENTES

END
GO


--PROCEDIMIENTO: INSERTAR DE SOFTWARE 

CREATE PROCEDURE InsertarSoftware
@OS VARCHAR(50),
@OSV VARCHAR(50),
@Arquitectura VARCHAR(50),
@OSNombre VARCHAR(50),
@OSDescripcion VARCHAR(50),
@ZO VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO SOFTWARE(SISTEMA_OPERATIVO,VERSION_SO,ARQUITECTURA,NOMBRE_SO,DESCRIPCION_SO,ZONA_HORARIA,FECHA_ACTUALIZACION)
VALUE(@OS,@OSV,@Arquitectura,@OSNombre,@OSDescripcion,@ZO,@FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE HARDWARE 

CREATE PROCEDURE InsertarHardware
@Procesador VARCHAR(50),
@Generacion CHAR(50),
@RamFisico VARCHAR(50),
@RamModelo VARCHAR(50),
@AlmacenamientoFisico VARCHAR(50),
@AlmacenamientoModelo VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO SOFTWARE(PROCESADOR,GENERACION,RAM_FISICO,RAM_MODELO,ALMACENAMIENTO_FISICO,ALMACENAMIENTO_MODELO,FECHA_ACTUALIZACION)
VALUE(@Procesador,@Generacion,@Arquitectura,@RamFisico,@RamModelo,@AlmacenamientoFisico,@AlmacenamientoModelo,@FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE RED 

CREATE PROCEDURE InsertarRed
@NombreRed VARCHAR(50),
@TipoAdaptador VARCHAR(50),
@TipoProducto VARCHAR(50),
@Instalado CHAR(50),
@IP VARCHAR(50),
@MascaraSubRed VARCHAR(50),
@PuertoEnlace VARCHAR(50),
@DHCP VARCHAR(50),
@MAC VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO RED(NOMBRE_RED,TIPO_ADAPTADOR,TIPO_PRODUCTO,INSTALADO,IP,MASCARA_SUB_RED,PUERTO_ENLACE,DHCP,MAC,FECHA_ACTUALIZACION)
VALUE(@NombreRed,@TipoAdaptador,@TipoProducto,@Instalado,@IP,@MascaraSubRed,@PuertoEnlace,@DHCP,@MAC,@FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE COMPONENTES EQUIPO

CREATE PROCEDURE InsertarComponetesEquipo
@DescripcionComponente VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME = current_timestamp
BEGIN

INSERT INTO COMPONENTEEQUIPO (DESCRIPCION_COMPONENTE,FECHA_ACTUALIZACION)
VALUES (@DescripcionComponente,@FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE COMPONENTES 

CREATE PROCEDURE InsertarComponetes
@IDEC INT,
@MarcaComponente VARCHAR(50),
@ModeloComponente VARCHAR(50),
@SerialComponente VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME = current_timestamp
BEGIN

INSERT INTO Componentes (ID_EQUIPO_COMPONENTE,MARCA_COMPONENTE,MODELO_COMPONENTE,SERIAL_COMPONENTE, FECHA_ACTUALIZACION)
VALUES (@IDEC, @MarcaComponente, @ModeloComponente, @SerialComponente, @FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE TIPO EQUIPO 

CREATE PROCEDURE InsertarTipoEquipo
@DescripcionTipo VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO TIPOEQUIPO(DESCRIPCION_COMPONENTE)
VALUE(@DescripcionTipo,@FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE COMPUTADORA 

CREATE PROCEDURE InsertarComputadora
@IdTipo INT,
@Marca VARCHAR(50),
@Modelo VARCHAR(50),
@Serial VARCHAR(50),
@IdHardware INT,
@IdSoftware INT,
@IdRed INT,
@IdUnidades INT,
@IdComponentes INT
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO COMPUTADORA(ID_TIPO,MARCA,MODELO,SERIAL,ID_HARDWARE,ID_SOFTWARE,ID_RED,ID_UNIDADES,ID_COMPONENTES,FECHA_ACTUALIZACION)
VALUE(@IdTipo,@Marca,@Modelo,@Serial,@IdHardware,@IdSoftware,@IdRed,@IdUnidades,@IdComponentes,@FechaModicacion)

END
GO

--PROCEDIMIENTO: INSERTAR DE TIPO UNIDADES 

CREATE PROCEDURE InsertarUnidades
@IdCPU INT,
@Unidad CHAR(50),
@NombreUnidad VARCHAR(50),
@EspacioTotal VARCHAR(50),
@EspacioLibre VARCHAR(50),
@SistemaArchivo VARCHAR(50)
AS
DECLARE @FechaModicacion DATETIME= current_timestamp
BEGIN

INSERT INTO UNIDADES(ID_CPU,UNIDAD,NOMBRE_UNIDAD,ESPACIO_TOTAL,ESPACIO_LIBRE,SISTEMA_ARCHIVO,FECHA_ACTUALIZACION)
VALUE(@IdCPU,@Unidad,@NombreUnidad,@EspacioTotal,@EspacioLibre,@SistemaArchivo,@FechaModicacion)

END
GO








--PROCEDIMIENTO: CONSULTA DE COMPONENTES 

--PROCEDIMIENTO: CONSULTA DE COMPONENTES 

--EJECUCION DEL PROCEDIMIENTO: BuscarCompoentes_CMINVENTARIOTI


EXEC PRUEBA001 'MARCOS',1;
GO

										------------PRUEBA-------------


--PRUEBA DE INSERCCION DE FECHA (FUNCIONA)
CREATE PROCEDURE PRUEBA0
@DESCRIPCIONCOMPONENTE varchar(50)
AS
declare @FechaModicacion datetime = current_timestamp
BEGIN
INSERT INTO COMPONENTEEQUIPO (DESCRIPCION_COMPONENTE,FECHA_ACTUALIZACION)

VALUES (@DESCRIPCIONCOMPONENTE,@FechaModicacion)

END
GO

CREATE PROCEDURE PRUEBA001
@DE VARCHAR(50),
@ID VARCHAR(50) 
AS
declare @FA datetime = current_timestamp
BEGIN
UPDATE       COMPONENTEEQUIPO
SET                FECHA_ACTUALIZACION = @FA, DESCRIPCION_COMPONENTE = @DE
WHERE (ID_EQUIPO_COMPONENTE=@ID)
END
GO



--EJECUCION DE PROCESOS DE FECHA:

--EXTRACCION DE FECHA COMPLETA
SELECT GETDATE()
--EXTRACCION DE LAS PARTES DE LA FECHA
SELECT DATEPART(YEAR,GETDATE())
SELECT DATEPART(MONTH,GETDATE())
SELECT DATEPART(DAY,GETDATE())
--EXTRACCION DEL MES EN NOMBRE
SELECT DATENAME(MONTH,GETDATE())
--EXTRACCION DE LA FECHA MAS AUMENTO DE 5 DIAS MAS
SELECT DATEADD(DAY,5,'2020/10/02')
--CONTEO DE DIAS
SELECT DATEDIFF(DAY, '2020/01/02','2021/01/02')
