--CREACION DE DB
CREATE DATABASE CMINVENTARIOTI
GO

--DIRECCIONAMIENTO A LA DB
USE CMINVENTARIOTI
GO

--CREACION DE TABLAS
CREATE TABLE SOFTWARE (
ID_SOFTWARE INT PRIMARY KEY IDENTITY,
--ID_CPU VARCHAR(50) UNIQUE FOREIGN KEY REFERENCES COMPUTADORA(ID_CPU),
SISTEMA_OPERATIVO VARCHAR(50) NOT NULL,
VERSION_SO VARCHAR(50) NOT NULL,
ARQUITECTURA VARCHAR(50) NOT NULL,
NOMBRE_SO VARCHAR(50) UNIQUE,
DESCRIPCION_SO VARCHAR(50) NOT NULL,
ZONA_HORARIA VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO

CREATE TABLE HARDWARE (
ID_HARDWARE INT PRIMARY KEY IDENTITY,
--ID_CPU INT NOT NULL UNIQUE FOREIGN KEY REFERENCES,
PROCESADOR VARCHAR(50) NOT NULL,
GENERACION CHAR(50) NOT NULL,
RAM_FISICO VARCHAR(50) NOT NULL,
RAM_MODELO VARCHAR(50) NOT NULL,
ALMACENAMIENTO_FISICO VARCHAR(50) NOT NULL,
ALMACENAMIENTO_MODELO VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO

CREATE TABLE RED (
ID_RED INT PRIMARY KEY IDENTITY,
--ID_CPU VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES COMPUTADORA (ID_CPU),
NOMBRE_RED VARCHAR(50) NOT NULL,
TIPO_ADAPTADOR VARCHAR(50) NOT NULL,
TIPO_PRODUCTO VARCHAR(50) NOT NULL,
INSTALADO CHAR(50) NOT NULL,
IP VARCHAR(50) NOT NULL,
MASCARA_SUB_RED VARCHAR(50) NOT NULL,
PUERTO_ENLACE VARCHAR(50) NOT NULL,
DHCP VARCHAR(50) NOT NULL,
MAC VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO

CREATE TABLE COMPONENTEEQUIPO (
ID_EQUIPO_COMPONENTE INT PRIMARY KEY IDENTITY,
DESCRIPCION_COMPONENTE VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO

CREATE TABLE COMPONENTES (
ID_COMPONENTES INT PRIMARY KEY IDENTITY,
--ID_CPU VARCHAR(50) NOT NULL,
ID_EQUIPO_COMPONENTE INT FOREIGN KEY REFERENCES COMPONENTEEQUIPO (ID_EQUIPO_COMPONENTE),
MARCA_COMPONENTE VARCHAR(50) NOT NULL,
MODELO_COMPONENTE VARCHAR(50) NOT NULL,
SERIAL_COMPONENTE VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO
 
 CREATE TABLE TIPOEQUIPO (
ID_TIPO INT PRIMARY KEY IDENTITY,
DESCRIPCION_TIPO VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO
 
 CREATE TABLE COMPUTADORA (
ID_CPU INT PRIMARY KEY IDENTITY,
ID_TIPO INT FOREIGN KEY REFERENCES TIPOEQUIPO(ID_TIPO),
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL,
SERIAL VARCHAR(50) NOT NULL,
--ID_NOMBRE VARCHAR(50) FOREIGN KEY REFERENCES SOFTWARE(ID_NOMBRE),
ID_HARDWARE INT FOREIGN KEY REFERENCES HARDWARE (ID_HARDWARE),
ID_SOFTWARE INT FOREIGN KEY REFERENCES SOFTWARE (ID_SOFTWARE),
ID_RED INT FOREIGN KEY REFERENCES RED (ID_RED),
ID_UNIDADES INT NOT NULL, --FOREIGN KEY REFERENCES UNIDADES (ID_UNIDADES),
ID_COMPONENTES INT FOREIGN KEY REFERENCES COMPONENTES (ID_COMPONENTES),
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO

CREATE TABLE UNIDADES (
ID_UNIDADES INT PRIMARY KEY IDENTITY,
ID_CPU INT FOREIGN KEY REFERENCES COMPUTADORA (ID_CPU),
UNIDAD CHAR(50) NOT NULL,
NOMBRE_UNIDAD VARCHAR(50) NOT NULL,
ESPACIO_TOTAL VARCHAR(50) NOT NULL,
ESPACIO_LIBRE VARCHAR(50) NOT NULL,
SISTEMA_ARCHIVO VARCHAR(50) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
FECHA_ACTUALIZACION DATETIME)
GO


										 ------------------------MODIFICAR-------------------------

ALTER TABLE COMPONENTES
add FOREIGN KEY DEFAULT TAG ID_CPU REFERENCES COMPUTADORA [ID_CPU]
 
GO

/*
--Agregar Columna--
ADD ID_CPU INT NOT NULL
--Modificarl Columna--
ALTER ID_CPU INT NOT NULL
*/